hydra:
  run:
    dir: outputs/n_gen:${rl_script_args.n_gen}_prompt_type:${rl_script_args.prompt_type}

lamorel_args:
  distributed_setup_args:
    n_rl_processes: 1
    n_llm_processes: 1

  accelerate_args:
    config_file: accelerate/default_config.yaml
    machine_rank: 0
    num_machines: 1
    num_processes: 2
    cpu:

  llm_args:
    model_type: causal
    model_path: /Users/tristankarch/Repo/semantic-goal-sampler/src/model_files/distilgpt2
    model_parallelism_size: 1
    minibatch_size: 32

rl_script_args:
  path: ???
  task_idx: 13
  n_gen: 1000
  n_goals: 20
  prompt_type: 'open' # 'predicate'
  generation_type: 'deter' #'deter'
  batch_size_gen: 10