lamorel_args:
  distributed_setup_args:
    n_rl_processes: 1
    n_llm_processes: 1

  accelerate_args:
    config_file: accelerate/default_config.yaml
    machine_rank: ???
    main_process_ip: ???
    num_machines: 1
    num_processes: 2

  llm_args:
    model_type: seq2seq
    model_path: /gpfsscratch/rech/imi/uwv18kd/model_parameters/T0pp
    model_parallelism_size: 4
    minibatch_size: 32

rl_script_args:
  path: ???
  task_idx: 13
  n_gen: 3
  n_goals: 10
  prompt_type: 'open'
  do_sample: True
  temperature: 1
  top_p: 0.5
  num_return_sequences: 5
  batch_size_gen: 2
