device: 'cpu'

# LLM parameters
#llm_model_path: '/Users/tristankarch/Repo/semantic-goal-sampler/src/model_files/roberta2gpt2-daily-dialog'
llm_model_path: '/gpfsscratch/rech/imi/uwv18kd/model_parameters/T0pp'

# Prompting parameters
n_gen: 500
n_goals: 50
prompt_type: 'open'

# Generation parameters
do_sample: True
temperature: 1
top_p: 0.5
top_k : 0
num_return_sequences: 5
